services:
  app-service:
    build: .
    container_name: hcp.torrents
    ports:
      - "6060:8080"  
    restart: always
    env_file:
      - .env
    networks:
      - hcp-network

networks:
  hcp-network:
    external: true
