name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  prepare-env:
    runs-on: [self-hosted] # Укажите ваш раннер (тот же, где деплой)
    steps:
      - name: Create .env file
        run: |
          # Переходим в папку проекта и записываем секрет в ${{ github.event.repository.name }}/.env
          mkdir -p ${{vars.DEPLOY_PATH}}/${{ github.event.repository.name }}/HCP.Torrents/
          echo "TORRENTHOST=http://host.docker.internal:8080" > ${{vars.DEPLOY_PATH}}/${{ github.event.repository.name }}/HCP.Torrents/.env 
          echo "BOTAPI=${{ secrets.BOTAPI }}" >> ${{vars.DEPLOY_PATH}}/${{ github.event.repository.name }}/HCP.Torrents/.env 
          echo "ADMIN=${{ secrets.ADMIN }}" >> ${{vars.DEPLOY_PATH}}/${{ github.event.repository.name }}/HCP.Torrents/.env 
  call-deploy:
    needs: [prepare-env]
    uses: leoserverteam/DevOpsTemplates/.github/workflows/dotnetcompose.yml@main
    with:
      project_name: "${{ github.event.repository.name }}"
